spring:
  rabbitmq:
    host: 192.168.192.132
    port: 5672
    username: guest
    password: guest
    template:
      retry:
        enabled: true # 代理链接丢失、启用重试AmqpTemplate
        initial-interval: 2s # 代理链接丢失、启用重试AmqpTemplate